<a href="https://colab.research.google.com/github/trodman201/Data-3000/blob/homeworkkkkkkkkkkk/Anime_vs__Manga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#anime
nRowsRead = 13000

df_anime = pd.read_csv('MAL-anime.csv.zip', delimiter=',', nrows=nRowsRead)

df_anime.dataframeName = 'AL-anime.csv.zip'

nRow, nCol = df_anime.shape

In [ ]:
print(df_anime.head())

   Unnamed: 0                                           Title   Rank     Type  \
0           0                               Net-juu no Susume   1568       TV
1           1  Neon Genesis Evangelion: The End of Evangelion     99    Movie
2           2                                         Templex  11445    Movie
3           3                                        s.CRY.ed   2248       TV
4           4                  Toaru Majutsu no Index-tan III   6679  Special

  Episodes                Aired  Members  \
0       10  Oct 2017 - Dec 2017   450968
1        1  Jul 1997 - Jul 1997   883576
2        1          2015 - 2015      538
3       26  Jul 2001 - Dec 2001    81283
4        2  Dec 2018 - Apr 2019    11370

                                            page_url  \
0  https://myanimelist.net/anime/36038/Net-juu_no...
1  https://myanimelist.net/anime/32/Neon_Genesis_...
2        https://myanimelist.net/anime/40721/Templex
3           https://myanimelist.net/anime/168/sCRYed
4  https://myanimelist.net/anime/39094/Toaru_Maju...

                                           image_url  Score
0  https://cdn.myanimelist.net/r/100x140/images/a...   7.55
1  https://cdn.myanimelist.net/r/100x140/images/a...   8.55
2  https://cdn.myanimelist.net/r/100x140/images/a...   5.29
3  https://cdn.myanimelist.net/r/100x140/images/a...   7.36
4  https://cdn.myanimelist.net/r/100x140/images/a...   6.44

In [ ]:
#manga
nRowsRead = 18000

df_manga = pd.read_csv('MAL-manga.csv.zip', delimiter=',', nrows=nRowsRead)

df_manga.dataframeName = 'AL-manga.csv.zip'

nRow, nCol = df_manga.shape

In [ ]:
print(df_manga.head())

   Unnamed: 0             Title   Rank      Type Volumes            Published  \
0           0       City Hunter    460     Manga      35  Feb 1985 - Nov 1991
1           1     Keijo!!!!!!!!   4532     Manga      18  Jul 2013 - Apr 2017
2           2              Rain   1808     Manga       ?           Nov 2008 -
3           3  Hidari no Futari  17377  One-shot       ?          2011 - 2011
4           4      Odd Girl Out    953    Manhwa       ?           May 2015 -

   Members                                           page_url  \
0    14690      https://myanimelist.net/manga/792/City_Hunter
1    12689          https://myanimelist.net/manga/56505/Keijo
2    12021           https://myanimelist.net/manga/17237/Rain
3     1010  https://myanimelist.net/manga/26610/Hidari_no_...
4     4968  https://myanimelist.net/manga/119521/Odd_Girl_Out

                                           image_url  Score
0  https://cdn.myanimelist.net/r/100x140/images/m...   8.16
1  https://cdn.myanimelist.net/r/100x140/images/m...   7.31
2  https://cdn.myanimelist.net/r/100x140/images/m...   7.67
3  https://cdn.myanimelist.net/r/100x140/images/m...   5.95
4  https://cdn.myanimelist.net/r/100x140/images/m...   7.90

In [ ]:
# Assuming df1 is your DataFrame containing anime data
# Read the CSV file into a DataFrame
df= pd.read_csv('MAL-anime.csv.zip', delimiter=',')

# Filter the DataFrame to include only anime with manga adaptations
anime_with_manga = df[df['Manga'] == 'Yes']

# Now 'anime_with_manga' contains only the rows where the 'Manga' column is 'Yes'
# You can then use this DataFrame for further analysis or processing

KeyError: 'Manga'

In [ ]:
anime_w_manga = pd.merge(df_anime, df_manga, left_on=['Title'], right_on=['Title'], how='inner', suffixes=('_anime', '_manga'))
anime_w_manga

,Unnamed: 0_anime,Title,Rank_anime,Type_anime,Episodes,Aired,Members_anime,page_url_anime,image_url_anime,Score_anime,Unnamed: 0_manga,Rank_manga,Type_manga,Volumes,Published,Members_manga,page_url_manga,image_url_manga,Score_manga
0,0,Net-juu no Susume,1568,TV,10,Oct 2017 - Dec 2017,450968,https://myanimelist.net/anime/36038/Net-juu_no...,https://cdn.myanimelist.net/r/100x140/images/a...,7.55,5424,4230,Manga,?,Oct 2013 - Jul 2015,5893,https://myanimelist.net/manga/86648/Net-juu_no...,https://cdn.myanimelist.net/r/100x140/images/m...,7.34
1,3,s.CRY.ed,2248,TV,26,Jul 2001 - Dec 2001,81283,https://myanimelist.net/anime/168/sCRYed,https://cdn.myanimelist.net/r/100x140/images/a...,7.36,14242,11502,Manga,5,May 2001 - Apr 2002,2106,https://myanimelist.net/manga/517/sCRYed,https://cdn.myanimelist.net/r/100x140/images/m...,6.78
2,10,Banana Fish,133,TV,24,Jul 2018 - Dec 2018,814329,https://myanimelist.net/anime/36649/Banana_Fish,https://cdn.myanimelist.net/r/100x140/images/a...,8.48,17030,74,Manga,19,Apr 1985 - Mar 1994,52440,https://myanimelist.net/manga/756/Banana_Fish,https://cdn.myanimelist.net/r/100x140/images/m...,8.63
3,13,Romantic Killer,524,ONA,12,Oct 2022 - Oct 2022,159661,https://myanimelist.net/anime/52865/Romantic_K...,https://cdn.myanimelist.net/r/100x140/images/a...,8.06,492,5801,Manga,4,Jul 2019 - Jun 2020,4953,https://myanimelist.net/manga/127138/Romantic_...,https://cdn.myanimelist.net/r/100x140/images/m...,7.20
4,20,Keijo!!!!!!!!,4285,TV,12,Oct 2016 - Dec 2016,389224,https://myanimelist.net/anime/32686/Keijo,https://cdn.myanimelist.net/r/100x140/images/a...,6.93,1,4532,Manga,18,Jul 2013 - Apr 2017,12689,https://myanimelist.net/manga/56505/Keijo,https://cdn.myanimelist.net/r/100x140/images/m...,7.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2084,12737,Beck,250,TV,26,Oct 2004 - Mar 2005,328103,https://myanimelist.net/anime/57/Beck,https://cdn.myanimelist.net/r/100x140/images/a...,8.29,13078,51,Manga,34,Feb 2000 - Jun 2008,74038,https://myanimelist.net/manga/145/Beck,https://cdn.myanimelist.net/r/100x140/images/m...,8.69
2085,12740,Da Zhu Zai,6635,ONA,12,Aug 2019 - Oct 2019,6567,https://myanimelist.net/anime/40233/Da_Zhu_Zai,https://cdn.myanimelist.net/r/100x140/images/a...,6.45,2427,8148,Manhua,?,Apr 2014 -,2227,https://myanimelist.net/manga/97798/Da_Zhu_Zai,https://cdn.myanimelist.net/r/100x140/images/m...,7.03
2086,12747,Kokoro ga Sakebitagatterunda.,883,Movie,1,Sep 2015 - Sep 2015,320711,https://myanimelist.net/anime/28725/Kokoro_ga_...,https://cdn.myanimelist.net/r/100x140/images/a...,7.82,7679,3315,Manga,4,Jul 2015 - Jul 2016,2362,https://myanimelist.net/manga/91109/Kokoro_ga_...,https://cdn.myanimelist.net/r/100x140/images/m...,7.44
2087,12760,Black Blood Brothers,3554,TV,12,Sep 2006 - Nov 2006,101444,https://myanimelist.net/anime/1498/Black_Blood...,https://cdn.myanimelist.net/r/100x140/images/a...,7.10,12479,5657,Light-Novel,11,Jul 2004 - May 2006,773,https://myanimelist.net/manga/23566/Black_Bloo...,https://cdn.myanimelist.net/r/100x140/images/m...,7.21
2088,12768,Ribbon no Kishi,5272,TV,52,Apr 1967 - Apr 1968,5106,https://myanimelist.net/anime/3024/Ribbon_no_K...,https://cdn.myanimelist.net/r/100x140/images/a...,6.72,1723,4746,Manga,3,Jan 1953 - Jan 1956,2984,https://myanimelist.net/manga/1676/Ribbon_no_K...,https://cdn.myanimelist.net/r/100x140/images/m...,7.29

In [ ]:
dates = anime_w_manga[['Title','Published', 'Aired']]
dates

                              Title            Published                Aired
0                 Net-juu no Susume  Oct 2013 - Jul 2015  Oct 2017 - Dec 2017
1                          s.CRY.ed  May 2001 - Apr 2002  Jul 2001 - Dec 2001
2                       Banana Fish  Apr 1985 - Mar 1994  Jul 2018 - Dec 2018
3                   Romantic Killer  Jul 2019 - Jun 2020  Oct 2022 - Oct 2022
4                     Keijo!!!!!!!!  Jul 2013 - Apr 2017  Oct 2016 - Dec 2016
...                             ...                  ...                  ...
2084                           Beck  Feb 2000 - Jun 2008  Oct 2004 - Mar 2005
2085                     Da Zhu Zai           Apr 2014 -  Aug 2019 - Oct 2019
2086  Kokoro ga Sakebitagatterunda.  Jul 2015 - Jul 2016  Sep 2015 - Sep 2015
2087           Black Blood Brothers  Jul 2004 - May 2006  Sep 2006 - Nov 2006
2088                Ribbon no Kishi  Jan 1953 - Jan 1956  Apr 1967 - Apr 1968

[2089 rows x 3 columns]

In [ ]:
filtered_dates = dates[dates['Published'] < dates['Aired']]
filtered_dates
#probably drop the manga that has the least difference in date for data analysis

                              Title            Published                Aired
0                 Net-juu no Susume  Oct 2013 - Jul 2015  Oct 2017 - Dec 2017
2                       Banana Fish  Apr 1985 - Mar 1994  Jul 2018 - Dec 2018
3                   Romantic Killer  Jul 2019 - Jun 2020  Oct 2022 - Oct 2022
4                     Keijo!!!!!!!!  Jul 2013 - Apr 2017  Oct 2016 - Dec 2016
5            Toaru Majutsu no Index           Apr 2007 -  Oct 2008 - Mar 2009
...                             ...                  ...                  ...
2080                          Karin  Apr 2003 - Feb 2008  Nov 2005 - May 2006
2084                           Beck  Feb 2000 - Jun 2008  Oct 2004 - Mar 2005
2085                     Da Zhu Zai           Apr 2014 -  Aug 2019 - Oct 2019
2086  Kokoro ga Sakebitagatterunda.  Jul 2015 - Jul 2016  Sep 2015 - Sep 2015
2087           Black Blood Brothers  Jul 2004 - May 2006  Sep 2006 - Nov 2006

[1062 rows x 3 columns]